apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: assignment2
spec:
  containers:
  - name: k8s-demo
    image: nginx
    ports:
    - name: nodejs-port
      containerPort: 80
  - name: k8s-demo
    image: afakharany/watcher
